### PR TITLE
Allow a regex as matching a pattern if it begins and ends with a `/`

### PR DESCRIPTION
**Pull request by marcbachmann**

### CODE REVIEW

**Comment by mikecrittenden** [comment]
Awesome idea, thanks!

**Comment by marcbachmann** [comment]
You're welcome. Thanks to you for the initial work and maintenance.

**Comment by pmalecka** [comment]
Marc, it seems that after this change - the site filter stopped working on me. My browser console seems to complain that '$1'.test is not a valid expression.
Should it perhaps be like this? 
`if (/^\/.*\/$/, '$1'.test(glob)) return new RegExp(glob.replace(/^\/(.*)\/$/, '$1'))`

**Comment by marcbachmann** [comment]
weird. of course

**Comment by pmalecka** [comment]
Whoa, quick response, thanks! Took me a while to get my head around that oneliner.

**Comment by mikecrittenden** [comment]
This for the fix here @marcbachmann - I guess this functionality isn't super commonly used. Just pushed!

**Pull request merged**
