### PR TITLE
Add "Search in focused window only" option for "Jump to tab or URL"

### PR DESCRIPTION
**Pull request by xcv58**
This fixes the #57

### CODE REVIEW

**Comment by mikecrittenden** [comment]
Looks great! I'll push a release with this included tomorrow. Thanks!

**Comment by xcv58** [comment]
Great, thanks!

**Comment by xcv58** [comment]
@mikecrittenden did you release a new version?

**Comment by mikecrittenden** [comment]
@xcv58 not yet - I tried but it's been so long since I updated the npm dependencies that things were erroring out and then I ran out of time. I'm going to drop in the new version of https://github.com/yeoman/generator-chrome-extension and build from that, later today.

**Comment by xcv58** [comment]
@mikecrittenden Thank you for updates! And the generator-chrome-extension is really awesome.

**Comment by xcv58** [comment]
@mikecrittenden Thank you very much!

**Comment by mikecrittenden** [comment]
No problem, thanks again for the PR and apologies for the slowness!

**Pull request merged**
